server {
    listen 8080;
    root /usr/share/nginx/html;
    index SnekTake2.html;


    gzip on;
    gzip_types application/wasm application/javascript text/html text/css;

    add_header Cross-Origin-Opener-Policy same-origin;
    add_header Cross-Origin-Embedder-Policy require-corp;
}